vmware/pyvmomi

pyVmomi/SoapAdapter.py, tests/test_serializer.py
XML serialization does not work for certain types on Python 3. This is best illustrated by example:
On Python 2.7:
>>> val = pyVmomi.vim.vm.device.VirtualDeviceSpec.FileOperation()
>>> pyVmomi.SoapAdapter.Serialize(val)
'<object xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="urn:vim25" xsi:type="VirtualDeviceConfigSpecFileOperation"></object>'
>>> from six import text_type
>>> isinstance(val, text_type)
False
>>> val.replace
'replace'
On Python 3.4:
>>> val = pyVmomi.vim.vm.device.VirtualDeviceSpec.FileOperation()
>>> pyVmomi.SoapAdapter.Serialize(val)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/mstunes/projects/uwsimscripts2/lib/python3.4/site-packages/pyVmomi/SoapAdapter.py", line 154, in …
=> XML serialization for certain types is broken on Python 3

pyVim/connect.py, tests/fixtures/basic_container_view.yaml, tests/fixtures/iso8601_set_datetime.yaml, tests/fixtures/root_folder_parent.yaml, tests/fixtures/smart_connection.yaml, tests/fixtures/test_vm_config_iso8601.yaml, tests/fixtures/vm_nic_data.yaml
Also modify test fixtures to not expect an extra slash in uri from SmartConnect
=> Make SmartConnect respect custom SSLContexts during version check

docs/vim/vm/RelocateSpec.rst
I found a line that has no context on a document of `RelocateSpec`.
=> removed a blank line

pyVmomi/SoapAdapter.py, pyVmomi/VmomiSupport.py, tests/test_serializer.py
1. Remove the encode() helper method since it doesn't provide encoding in python3 at all.
2. In order to workaround the leading 'b' literal after encoding in python3,
we delay the encoding step and will encode the whole soap message instead of individual values.
3. Added separate cases to handle Enum, integer and float to make the serializtion process more clear.
=> Python3 fixes for SoapAdapter serializer.

pyVmomi/Differ.py
Python3 doesn't have long type so isinstance(obj, types.long) will fail. Replacing isinstance(obj, types.long) and isinstance(obj, types.int) with isinstance(obj, six.integer_types)
Also replaced isinstance(obj, str) with isinstance(obj, six.string_types) to handle all string types in python2 and 3.
=> Fix python3 error when evaluating if obj is primitive type

pyVmomi/ManagedMethodExecutorHelper.py
Replace Serialize() to SerializeToUnicode() in ManagedMethodExecuterHelper.py
In python3, the Serialize() produce bytes output in order to be consistent 
with python2 behavior. However bytes is not supported in pyVmomi in python3.
Use SerializeToUnicode() instead to serialize the content to unicode.
=> Replace Serialize() to SerializeToUnicode() in ManagedMethodExecuterHelper.py

pyVmomi/SoapAdapter.py, tests/test_serializer.py
We are developing a vmware extension on top of pyvmomi, and we need support for the Storage Monitoring Service API (See #35).
We have already added support for that API on our wrapper for pyvmomi (you can see our repository here: https://github.com/infinidat/infi.pyvmomi_wrapper).
The following changes are needed for the support of the extra API.
=> Refactoring to support SMS API

pyVmomi/VmomiSupport.py
pyvmomi objects can be resolved by the vmodl name, e.g. "vim.vm.RelocateSpec" or by the wsdl name, e.g. "vim.VirtualMachineRelocateSpec".
The wsdl name resolution uses "vim" as a hard-coded name, and doesn't resolve more wsdl namespaces like "sms" and "pbm"
This pull request allows accessing sms and pbm objects by their wsdl name, e.g. sms.VasaProviderSpec (instead of sms.provider.VasaProviderSpec) and pbm.PbmVvolType (instead of pbm.ServerObjectRef.VvolType), just like for 'vim'
=> Use urn map for attribute resolution from top-level names

pyVmomi/SoapAdapter.py, pyVmomi/VmomiSupport.py, tests/files/unknown_method.xml, tests/test_deserializer.py
VC is returning some internal managed method in 6.0. Looks like this issue
will be resolved in 6.5 server types as it will be public in 6.5. To tempoarily
workaound this issue, returning a dummy method and dummy obj instead of throwing
exception when client side can't understand the returned managed method.
=> Temporarily workaround issue #182 by creating dummy managed method

sample/getallvms.py
VM folders may contain vApps. If a vApp is detected, print its
child VMs.
A vApp may contain child vApps too, but since this is a rare
usecase, nested vApps and their child VMs are ignored.
Signed-off-by: Martin Mosegaard Amdisen <martin.amdisen@praqma.com>
=> Fix #351: Detect vApps in getallvms sample

sample/getallvms.py
Import vim so that sample code will run properly
Otherwise, will receive the following traceback:
`
Traceback (most recent call last):
File "getallvms.py", line 129, in <module>
main()
File "getallvms.py", line 124, in main
PrintVmInfo(vm)
File "getallvms.py", line 63, in PrintVmInfo
PrintVmInfo(c, depth+1)
File "getallvms.py", line 63, in PrintVmInfo
PrintVmInfo(c, depth+1)
File "getallvms.py", line 68, in PrintVmInfo
if isinstance(vm, vim.VirtualApp):
NameError: global name 'vim' is not defined
`
=> Import vim from pyVmomi

pyVim/connect.py
add parameter 'connectionPoolTimeout' in both SmartConnect and SmartConnectNoSSL
This PR is for issue #347, @tianhao64
=> add parameter 'connectionPoolTimeout' in both SmartConnect and SmartConnectNoSSL

pyVmomi/SoapAdapter.py
This prevents maximum recursion depth errors when referencing _HTTPSConnection.connect. The custom \_\_getattr\_\_ was a leftover from https://github.com/vmware/pyvmomi/commit/21a5d52e6a9f0742c14640edead762d2eda8951a which removed the '_wrapped' attribute.
=> Fix #487: Remove custom __getattr__ in _HTTPSConnection

pyVim/sso.py, requirements.txt
sso.py can be used to get bearer or hok token from sts service. There are two dependencies needed to support sso.py: lxml and pyOpenSSL. Will add samples to demo basic usage to community samples repo later.
=> add sso.py to support get bearer/hok token from sso server

docs/vim/vm/GuestInfo.rst
According to the code, guest os not running state is : "notRunning"
```python
CreateEnumType("vim.vm.GuestInfo.GuestState", "VirtualMachineGuestState", "vim.version.version1", ["running", "shuttingDown", "resetting", "standby", "notRunning", "unknown"])
```
=> [DOC] Fix guest os state

pyVmomi/SoapAdapter.py, tests/test_vim_session_oriented_stub.py
original code didn't retry when unauthenticated issues happen. Tracking by issue #239. PR #286 has been closed because related check didn't pass
=> Fix for issue 239

pyVmomi/SoapAdapter.py
Add more info to header for pyvmomi client.
After the change the user agent will be:
'pyvmomi Python/3.6.3 (Windows; 10; AMD64)'
'pyvmomi Python/2.7.8 (Linux; 2.6.32-642.6.2.el6.x86_64; x86_64)'
'pyvmomi Python/3.6.2 (Darwin; 15.6.0; x86_64)'
Signed-off-by: Tianhao He <het@vmware.com>
=> Add more telemetry info to pyvmomi client

test-requirements.txt, tests/__init__.py
This fixes #735 
```
jking@dvm:~/pyvmomi$ tox
GLOB sdist-make: /home/jking/pyvmomi/setup.py
py27 create: /home/jking/pyvmomi/.tox/py27
py27 installdeps: -rtest-requirements.txt
py27 inst: /home/jking/pyvmomi/.tox/dist/pyvmomi-6.7.1.zip
py27 installed: certifi==2018.10.15,chardet==3.0.4,contextlib2==0.5.5,extras==1.0.0,filelock==3.0.10,fixtures==3.0.0,funcsigs==1.0.2,idna==2.7,linecache2==1.0.0,mock==2.0.0,pbr==5.1.0,pkg-resources==0.0.0,pluggy==0.8.0,py==1.7.0,python-mimeparse==1.6.0,pyvmomi==6.7.1,PyYAML==3.13,requests==2.20.0,six==1.11.0,testtools==2.3.0,toml==0.10.0,tox==3.5.3,traceback2==1.4.0,unittest2==1.1.0,urllib3==1.24.1,vcrpy==1.13.0,virtualenv==16.1.0,wrapt==1.10.11
py27 runtests: PYTHONHASHSEED='1076960615'
py27 runtests: commands[0] | python setup.py test
running test
running …
```
=> fix vcrpy version requirement for testing, reduce verbosity of test log

pyVim/connect.py, pyVmomi/SoapAdapter.py, test-requirements.txt, tests/fixtures/http_proxy.yaml, tests/test_connect.py
- ensure the proxy configuration is passed to `__GetElementTree()`
- ruse @blacksponge fix for the  `SSLTunnelConnection` class
- remove `test_ssl_tunnel_http_failure` because the error will happen later
closes: #620
closes: #567
closes: #198
=> support CONNECT based proxies

pyVim/connect.py
Change the default value of 'verify' parameter to 'True'.
Note ::
This is the derived contribution of Mr. @madblobfish from pull request [819](https://github.com/vmware/pyvmomi/pull/819).
=> Modify 'verify' parameter's default value to 'True'

tests/test_json.py
test_json tox cases were failed with 7.0 bindings. The .expect files needs to be updated. The design of test_json needs to be revised otherwise we have issue every time with new bindings.
Skipping the tests till tests are revised
=> skipped test_json for 7.0 release

README.rst
Square brackets are interpreted by some shells (e.g. zsh) so it's better
to surround them with quotes when used on the command line.
=> Quote arguments with square brackets
